service: sky9

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
  environment:
    AccountTableName: Account

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  GetAccount: ${file(./functions/account.yml):GetAccount}
  GetAccounts: ${file(./functions/account.yml):GetAccounts}
  CreateAccount: ${file(./functions/account.yml):CreateAccount}

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      port: 8000


resources:
  - ${file(./resources/dynamoDB.yml)}
  
