service: sky9

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
  environment:
    AccountTableName: Account

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  createAccount:
    handler: src/handler/account-handler.createAccount
    events:
      - http:
          path: accounts
          method: post
  getAccounts:
    handler: src/handler/account-handler.getAccounts
    events:
      - http:
          path: accounts
          method: get
  getAccount:
    handler: src/handler/account-handler.getAccount
    events:
      - http:
          path: account/{id}
          method: get

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      port: 8000

resources:
  Resources:
    Account:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Account
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          # - AttributeName: name
          #   AttributeType: S
          # - AttributeName: email
          #   AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  
