service: sky9

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-2
  environment:
    AccountTableName: Account

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  GetAccount: ${file(./functions/account.yml):getAccount}
  GetAccounts: ${file(./functions/account.yml):getAccounts}
  CreateAccount: ${file(./functions/account.yml):createAccount}
  UpdateAccount: ${file(./functions/account.yml):updateAccount}
  DeleteAccount: ${file(./functions/account.yml):DeleteAccount}
custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      port: 8000


resources:
  - ${file(./resources/dynamoDB.yml)}
  
