Resources:
  Account:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Account-${self:provider.stage}
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH