service: sky9

provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
    - Effect: Allow
      Action:
        - cloudtrail:LookupEvents
        - organizations:ListAccounts
        - budgets:*
        - sts:GetCallerIdentity
      Resource: "*"
  runtime: nodejs10.x
  stage: ${opt:stage, "test"}
  region: ${opt:region, "eu-west-1"}
  environment: ${file(./sls-env.yml):${self:provider.stage}}

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  GetAccount: ${file(./functions/account.yml):getAccount}
  GetAccounts: ${file(./functions/account.yml):getAccounts}
  CreateAccount: ${file(./functions/account.yml):createAccount}
  UpdateAccount: ${file(./functions/account.yml):updateAccount}
  DeleteAccount: ${file(./functions/account.yml):deleteAccount}
  SyncAccounts: ${file(./functions/account.yml):syncAccounts}
custom:
  dynamodb:
    stages:
      - local
    start:
      migrate: true
      port: 8000
  serverless-offline:
      port: 4000

resources:
  - ${file(./resources/dynamoDB.yml)}
  